USE [master]
GO

/****** Object:  Database [CarRental]    Script Date: 2018-12-23 21:45:58 ******/
CREATE DATABASE [CarRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRental', FILENAME = N'C:\Users\Łukasz\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\CarRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarRental_log', FILENAME = N'C:\Users\Łukasz\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\CarRental.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CarRental] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRental] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [CarRental] SET ANSI_NULLS ON 
GO

ALTER DATABASE [CarRental] SET ANSI_PADDING ON 
GO

ALTER DATABASE [CarRental] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [CarRental] SET ARITHABORT ON 
GO

ALTER DATABASE [CarRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRental] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [CarRental] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [CarRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRental] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [CarRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRental] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRental] SET RECOVERY FULL 
GO

ALTER DATABASE [CarRental] SET  MULTI_USER 
GO

ALTER DATABASE [CarRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRental] SET QUERY_STORE = OFF
GO

USE [CarRental]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CarRental] SET  READ_WRITE 
GO

